---
title: "07 29 2020 - Joe Kelly"
author: "Brett Moxham"
date: "29/07/2020"
output: html_document
---

On July 29th 2020 Joe Kelly was suspended for 8 games, [throwing behind Astros hitters](https://mlb.nbcsports.com/2020/07/29/joe-kelly-suspended-eight-games-by-major-league-baseball/). He did not hit anyone, and was not ejected at the time. Lets examine.

TLDR: Bull Shit


## Lets get our Data and Load our Libraries
```{r}
library(tidyverse)
library(ggtext)

people <- c("Joe Kelly", "Dave Roberts", paste("Entirety of Astros Roster (2017-2018)"))
suspensions <- c(8,1,0)  #Source: Rob Manfred 

data <- data.frame(people,suspensions)


img <- png::readPNG("images/Joe Kelly/joe-kelly.png")
img <- grid::rasterGrob(img, interpolate = TRUE)
```



```{r}
caption_joe <- tibble(text = c('8 games adjusted<br> to a 162 game season <br> equates to <b>22</b> games.', "1 game adjusted <br> to 162 a game season <br> equates to <b>3</b> games", "0 games adjusted <br> to a 162 game season <br> equates to <b>0</b> games."),
                      x = c(1.5, 2, 3),
                      y = c(7.35, 2, 0.8))




plot_joe <- ggplot(data, aes(reorder(people, -suspensions), suspensions))+
  geom_col(width = 0.5, fill = "dodgerblue", alpha =0.5)+
  annotate(
    geom = "curve", x =1.43, xend = 1.3, y = 7, yend = 6,curvature = 0,
           arrow = arrow(length = unit(2,"mm"))
    )+
  annotate(
    geom ="curve", x = 2, xend = 2, y = 1.6, yend = 1, curvature = 0,
          arrow = arrow(length = unit(2,"mm"))
  )+
  annotate(
  geom ="curve", x = 3, xend = 3, y = 0.4, yend = 0, curvature = 0,
        arrow = arrow(length = unit(2,"mm"))
  )+
  geom_richtext(data = caption_joe, aes(x,y, label = text), size = 4, fill = NA, label.color = NA)+
  geom_textbox(data = tibble(
    x = 3, y = 4.5,
    label = "Rob Manfred and Major League Baseball suspended Joe Kelly for <b>8</b> games for throwing <i>NEAR</i>, and <i>MOCKING</i> Astros hitters on July 28th. This penalty is excessive considering it accounts for 14% of the season, as well as considering that no suspensions were handed to Astros during their cheating scandal in 2017 - 2018"
  ), aes(x,y, label = label))+
  annotation_custom(
    img,
 xmin = 0.5, xmax = 3.5, ymin = 2.5, ymax = 6.5)+
  theme_minimal()+
  theme(
        plot.title = element_text(face = "bold", hjust = 0.5, size = rel(3.5)),
        plot.subtitle = element_text(face = "italic", hjust = 0.5),
        axis.text.x = element_text(face = "bold", color = "black", size = 13),
        axis.text.y = element_text(size = 10),
        axis.title.y = element_text(face ="bold"),
        plot.margin = margin(25,25,25,25)
        )+
  labs(
    x = NULL,
    y ="Total Suspensions (By Game)",
    title = "Suspensions Handed Out by MLB",
    subtitle = "This suspension brought to you by Rob Manfred.",
    caption ="bmoxO9 | #100DaysofCode #R4DS #RStats"
  )

ggsave("images/Joe Kelly/Joe_plot.png", plot_joe, height = 9, width = 15.75)

```

